### ISSUE TITLE
How to suspend?

### ISSUE THREAD

**Issue by subnut** [skarnet/s6-linux-init#2]
`s6-linux-init-hpr` has options to shutdown, halt and reboot... where's suspend ?

Yes, I am using `s6 + s6-rc + s6-linux-init` on my main machine. :P

P.S. What distro do you personally use? I'm curious. Mine's Artix.

**Comment by subnut** [comment]
Oh wait... this is the wrong repo....

**Comment by subnut** [comment]
Correct repo issue: skarnet/s6-linux-init#2

**Comment by skarnet** [comment]
@subnut suspend is not in the list of sysvinit shutdown commands which s6-linux-init-hpr emulates, and it makes sense: suspending a machine can be done at any time, it does not require a full shutdown procedure, so its place is not with an init/shutdown package. If you want to suspend your machine, your best bet is probably `pm-suspend`, from the `pm-utils` package.

I *could* add an option to `s6-linux-init-hpr` to make it suspend, but it would be very ad-hoc and I'd rather avoid it.

I am not tied to any particular distro and will use whatever a customer provides me with. My servers are hand-built and use no distro at all. If I had to use a distro on a server, I would choose Alpine; if I had to use a distro on a desktop, I would choose Adélie. But it really does not matter, I try to keep my work as distro-agnostic as possible and it's all that counts.

**Comment by subnut** [comment]
> If you want to suspend your machine, your best bet is probably pm-suspend, from the pm-utils package.

Thanks, that's actually what I needed...... But do you know of some other way? I had read somewhere (I am sorry I don't remember where) that we could do something like `echo -n "<some-number>"  >  <path-to-a-file>` to put the PC in suspend mode..

 `pm-utils` is unavailable in the repo, that's why I ask.

> My servers are hand-built and use no distro at all.

Woah!! :astonished:  How? 
Leave it.... This is enough for me to understand that you know linux/UNIX **much much** more than me...
Where did you get this knowledge from? Is there some book or some website? I also want to learn.

**Comment by skarnet** [comment]
> But do you know of some other way? I had read somewhere (I am sorry I don't remember where) that we could do something like `echo -n "<some-number>" > <path-to-a-file>` to put the PC in suspend mode..

I have no idea, sorry. I've never used a laptop with Linux. All I know is that there's an argument to the [reboot system call](https://man7.org/linux/man-pages/man2/reboot.2.html) that suspends.

> Where did you get this knowledge from? Is there some book or some website? I also want to learn.

 Exploration, experimentation, and *a lot* of time dedicated to doing it, and making a lot of mistakes 😄 I don't recommend going down that path unless you want to make it your job or specific area of expertise (which it is for me) because it's really time-consuming, and not scalable. But if you're interested, look up the "Linux From Scratch" documentation; it's imperfect, and way too complex because it focuses on GNU tools that aren't really suited for bootstrapping, but it will give you a good idea of the state of mind and the kind of work it requires, as well as a starting point.

**Comment by subnut** [comment]
> I have no idea, sorry. I've never used a laptop with Linux.

Nevermind, [I found it.](https://www.kernel.org/doc/Documentation/power/states.txt)

> But if you're interested, look up the "Linux From Scratch" documentation

Yes, I have heard about it.... Does it require knowledge of C? I haven't learnt C yet... (but I do intend to learn it in the future)

> and not scalable

ummm... why? I mean, linux runs everywhere, doesn't it? From servers to embedded systems. So why isn't the knowledge of the kernel (and the low-level architecture of Linux in general) scalable?

**Comment by skarnet** [comment]
You can build a Linux system from scratch without knowledge of C; however, you will need to know how to build a package, which frequently involves running gcc, and if something goes wrong then it is helpful to know the basics of debugging a package build (which is admittedly a very different skillset from C programming). It is definitely not for the faint of heart.

Building your own system, although very educational, is a heavy time investment when you're doing it on _one_ machine. I'm saying it's not scalable because if you have N machines to maintain, chances are you won't have the time to do all that work N times. Then you'll be tempted to write scripts in order to automate all the maintenance work on your N machines, and you will rely on these scripts more and more, but you'll soon find they're ugly and need reworking... and before you know it, you're building your own distribution. 😉 It's a classic mistake; everyone makes it. Avoid that by using the least bad distribution you can find if you have more than one machine to manage.

Knowledge is scalable, and always valuable; manual system administration is not.

**Comment by subnut** [comment]
@skarnet Your servers are hand-built, right? Do you use any package manager on them?
If yes, which one? If no, then how do you upgrade your software? 
Simply download the new version and `make && make install`?

**Comment by skarnet** [comment]
My servers are hand-built, I don't use any package manager, and indeed I upgrade by hand via `configure && make && make install`, just like in the old days 😄
It works for me because I only have two machines to maintain this way, and I consider the manual maintenance a part of the skillset I need to keep fresh, since I often get jobs involving packaging or diving into the entrails of building software.
If I had any more machines, I would probably use a distribution, for the ease of package management.

**Comment by john9631** [comment]
Should anyone be reading this thread using Arch or Oberun then pm-utils is available as an AUR.

So its simply a matter of cloning pm-utils and making & installing the package with:

`git clone https://aur.archlinux.org/pm-utils.git`  
`cd pm-utils/`  
`ls`  
`makepkg -si`

On my machine I use `sudo /usr/sbin/pm-suspend`  to suspend and `sudo 66-shutdown -r now` to shut down.
